<?php

namespace Proxies\__CG__\App\CoreBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Urunler extends \App\CoreBundle\Entity\Urunler implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'kutuno', 'uruncinsi', 'adet', 'firma', 'toplam', 'agirlik', 'markaliurunadet', 'fsizadet', 'gonderiyontemi', 'parent');
        }

        return array('__isInitialized__', 'id', 'kutuno', 'uruncinsi', 'adet', 'firma', 'toplam', 'agirlik', 'markaliurunadet', 'fsizadet', 'gonderiyontemi', 'parent');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Urunler $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setParent(\App\CoreBundle\Entity\Siparis $parent = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParent', array($parent));

        return parent::setParent($parent);
    }

    /**
     * {@inheritDoc}
     */
    public function getParent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParent', array());

        return parent::getParent();
    }

    /**
     * {@inheritDoc}
     */
    public function setKutuno($kutuno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKutuno', array($kutuno));

        return parent::setKutuno($kutuno);
    }

    /**
     * {@inheritDoc}
     */
    public function getKutuno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKutuno', array());

        return parent::getKutuno();
    }

    /**
     * {@inheritDoc}
     */
    public function setUruncinsi($uruncinsi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUruncinsi', array($uruncinsi));

        return parent::setUruncinsi($uruncinsi);
    }

    /**
     * {@inheritDoc}
     */
    public function getUruncinsi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUruncinsi', array());

        return parent::getUruncinsi();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdet($adet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdet', array($adet));

        return parent::setAdet($adet);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdet', array());

        return parent::getAdet();
    }

    /**
     * {@inheritDoc}
     */
    public function setToplam($toplam)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setToplam', array($toplam));

        return parent::setToplam($toplam);
    }

    /**
     * {@inheritDoc}
     */
    public function getToplam()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToplam', array());

        return parent::getToplam();
    }

    /**
     * {@inheritDoc}
     */
    public function setAgirlik($agirlik)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAgirlik', array($agirlik));

        return parent::setAgirlik($agirlik);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgirlik()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgirlik', array());

        return parent::getAgirlik();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setFsizadet($fsizadet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFsizadet', array($fsizadet));

        return parent::setFsizadet($fsizadet);
    }

    /**
     * {@inheritDoc}
     */
    public function getFsizadet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFsizadet', array());

        return parent::getFsizadet();
    }

    /**
     * {@inheritDoc}
     */
    public function setGonderiyontemi($gonderiyontemi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGonderiyontemi', array($gonderiyontemi));

        return parent::setGonderiyontemi($gonderiyontemi);
    }

    /**
     * {@inheritDoc}
     */
    public function getGonderiyontemi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGonderiyontemi', array());

        return parent::getGonderiyontemi();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarkaliurunadet($markaliurunadet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarkaliurunadet', array($markaliurunadet));

        return parent::setMarkaliurunadet($markaliurunadet);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarkaliurunadet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarkaliurunadet', array());

        return parent::getMarkaliurunadet();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirma($firma)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirma', array($firma));

        return parent::setFirma($firma);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirma()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirma', array());

        return parent::getFirma();
    }

}
